name: longship-rl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pyyaml>=6.0,<7
  - pyzmq>=26,<28
  - pip:
      - --extra-index-url https://pypi.nvidia.com
      - isaacsim[all,extscache]==5.1.0.0
      - mujoco==3.4.0
      - onnxruntime-gpu==1.23.2
      - cyclonedds==0.10.2
      - pyrealsense2>=2.55,<3
      - -e ./third_party/GR00T-WholeBodyControl/external_dependencies/unitree_sdk2_python
      - -e ./third_party/GR00T-WholeBodyControl/gear_sonic[sim]
